from easyfhe.fhe.ops import alignment


def normalize_bootstrap_mode(bootstrap_mode):
    mode = str(bootstrap_mode or "modraise_first").lower()
    aliases = {
        "classic": "modraise_first",
        "modraise_first": "modraise_first",
        "mod_raise_first": "modraise_first",
        "slots_first": "stc_first",
        "stc_first": "stc_first",
        "s2c_first": "stc_first",
    }
    try:
        return aliases[mode]
    except KeyError as exc:
        raise ValueError("bootstrap_mode must be one of: modraise_first, stc_first") from exc


def _require_supported_transform_mode(level_budget):
    if int(level_budget[0]) == 1 or int(level_budget[1]) == 1:
        raise NotImplementedError(
            "OpenFHE bootstrap does not support the linear-transform route; "
            f"both level_budget entries must be greater than 1, got {tuple(level_budget)}"
        )


def _validate_bootstrap_inputs(bootstrap_constants, bootstrap_plan):
    if bootstrap_constants is None:
        raise ValueError("homo_bootstrap requires bootstrap_constants generated by easyfhe.bs.openfhe.generate(ctx, ...)")
    if bootstrap_plan is None:
        raise ValueError("homo_bootstrap requires bootstrap_plan generated by easyfhe.bs.openfhe.generate(ctx, ...)")


def _target_output_limbs(crypto_context, bootstrap_plan, active_l0):
    planned = int(bootstrap_plan.post_bootstrap_levels)
    post_limbs = planned - (int(crypto_context.L) - int(active_l0))
    if post_limbs <= 0:
        raise ValueError(
            "bootstrap active L0 leaves no post-bootstrap depth: "
            f"post_bootstrap_levels={planned}, context L={crypto_context.L}, "
            f"active_l0={active_l0}"
        )
    return post_limbs + 1


# note: EvalBootstrap in ckksrns-fhe.cpp
def eval_bootstrap(
    ciphertext,
    cryptoContext,
    bootstrap_constants,
    bootstrap_plan,
    L0,
    bootstrap_mode="modraise_first",
    *,
    active_l0=None,
):
    _validate_bootstrap_inputs(bootstrap_constants, bootstrap_plan)

    if L0 is None:
        raise ValueError("bootstrap L0 must be explicit")
    _require_supported_transform_mode(bootstrap_plan.level_budget)

    mode = normalize_bootstrap_mode(bootstrap_mode)
    if mode == "stc_first":
        from .bootstrap_stc_first import eval_bootstrap_stc_first

        return eval_bootstrap_stc_first(
            ciphertext,
            cryptoContext,
            bootstrap_constants,
            bootstrap_plan,
            L0,
            active_l0=active_l0,
        )

    from .bootstrap_modraise_first import eval_bootstrap_modraise_first

    return eval_bootstrap_modraise_first(
        ciphertext,
        cryptoContext,
        bootstrap_constants,
        bootstrap_plan,
        L0,
        active_l0=active_l0,
    )


def homo_bootstrap(
    cipher,
    cryptoContext,
    bootstrap_constants,
    bootstrap_plan,
    L0,
    bootstrap_mode="modraise_first",
):
    plan_active_l0 = getattr(bootstrap_plan, "active_l0", None)
    if L0 is None and plan_active_l0 is not None:
        L0 = int(plan_active_l0)
    if L0 is None:
        raise ValueError("bootstrap L0 must be explicit unless it was fixed when generating the plan")
    active_l0 = int(L0)
    if not 1 <= active_l0 <= int(cryptoContext.L):
        raise ValueError(f"bootstrap L0 must be in [1, {cryptoContext.L}], got {active_l0}")
    if plan_active_l0 is not None and int(plan_active_l0) != active_l0:
        raise ValueError(
            "bootstrap constants were generated for a different active L0: "
            f"constants active_l0={int(plan_active_l0)}, requested active_l0={active_l0}"
        )

    result = eval_bootstrap(
        cipher,
        cryptoContext,
        bootstrap_constants,
        bootstrap_plan,
        L0=L0,
        bootstrap_mode=bootstrap_mode,
        active_l0=active_l0,
    )
    result = alignment.reduce_noise_to_one(result, cryptoContext)
    target_limbs = _target_output_limbs(cryptoContext, bootstrap_plan, active_l0)
    target_state = result.state.replace(
        cur_limbs=target_limbs,
        noise_deg=1,
    )
    if result.state != target_state:
        return alignment.align_to(
            result,
            target_state,
            cryptoContext,
        )
    return result
