from easyfhe.fhe.ops import alignment


def normalize_bootstrap_mode(bootstrap_mode):
    mode = str(bootstrap_mode or "modraise_first").lower()
    aliases = {
        "classic": "modraise_first",
        "modraise_first": "modraise_first",
        "mod_raise_first": "modraise_first",
        "slots_first": "stc_first",
        "stc_first": "stc_first",
        "s2c_first": "stc_first",
    }
    try:
        return aliases[mode]
    except KeyError as exc:
        raise ValueError("bootstrap_mode must be one of: modraise_first, stc_first") from exc


def _require_supported_transform_mode(level_budget):
    if int(level_budget[0]) == 1 or int(level_budget[1]) == 1:
        raise NotImplementedError(
            "OpenFHE bootstrap does not support the linear-transform route; "
            f"both level_budget entries must be greater than 1, got {tuple(level_budget)}"
        )


def _validate_bootstrap_inputs(bootstrap_constants, bootstrap_plan):
    if bootstrap_constants is None:
        raise ValueError("homo_bootstrap requires bootstrap_constants generated by easyfhe.bs.openfhe.generate(ctx, ...)")
    if bootstrap_plan is None:
        raise ValueError("homo_bootstrap requires bootstrap_plan generated by easyfhe.bs.openfhe.generate(ctx, ...)")


# note: EvalBootstrap in ckksrns-fhe.cpp
def eval_bootstrap(ciphertext, cryptoContext, bootstrap_constants, bootstrap_plan, L0, bootstrap_mode="modraise_first"):
    _validate_bootstrap_inputs(bootstrap_constants, bootstrap_plan)

    if L0 is None:
        raise ValueError("bootstrap L0 must be explicit")
    _require_supported_transform_mode(bootstrap_plan.level_budget)

    mode = normalize_bootstrap_mode(bootstrap_mode)
    if mode == "stc_first":
        from .bootstrap_stc_first import eval_bootstrap_stc_first

        return eval_bootstrap_stc_first(ciphertext, cryptoContext, bootstrap_constants, bootstrap_plan, L0)

    from .bootstrap_modraise_first import eval_bootstrap_modraise_first

    return eval_bootstrap_modraise_first(ciphertext, cryptoContext, bootstrap_constants, bootstrap_plan, L0)


def homo_bootstrap(cipher, cryptoContext, bootstrap_constants, bootstrap_plan, L0, bootstrap_mode="modraise_first"):
    result = eval_bootstrap(
        cipher,
        cryptoContext,
        bootstrap_constants,
        bootstrap_plan,
        L0=L0,
        bootstrap_mode=bootstrap_mode,
    )
    result = alignment.reduce_noise_to_one(result, cryptoContext)
    target_limbs = int(getattr(bootstrap_plan, "post_bootstrap_levels", 0)) + 1
    if target_limbs > 0 and result.state.cur_limbs > target_limbs:
        return alignment.align_to(
            result,
            result.state.replace(cur_limbs=target_limbs, noise_deg=1),
            cryptoContext,
        )
    return result
