import math

from easyfhe.fhe.ops import kernels as F
from easyfhe.fhe.ops import alignment
from easyfhe.fhe.ops import arithmetic
from easyfhe.fhe.ops import plaintext
from easyfhe.fhe.ops import rotation
from . import approx as bootstrap_approx


def coeffs_slots_conversion(ciphertext, transform_plan, constants, bootstrap_plan, cryptoContext):
    result = ciphertext
    strategy = bootstrap_plan.strategy
    hoist_strategy = {
        "normal_bsgs": "normal",
        "normal_giant": "ext_normal",
    }.get(strategy, "ext_double_hoist")
    is_ext = strategy != "normal_bsgs"

    for loop_pos, step in enumerate(transform_plan.steps):
        if loop_pos != 0:
            result = alignment.reduce_noise_to_one(result, cryptoContext)

        plaintext_batch = constants.plaintext(
            step.plaintext_name,
            cryptoContext.L - result.cur_limbs,
            step.plaintext_slots,
            cryptoContext,
            is_ext=is_ext,
        )
        result = rotation.hoisted_mac_sum(
            result,
            step.input_offsets,
            plaintext_batch,
            step.giant_offset,
            step.baby_step,
            cryptoContext,
            strategy=hoist_strategy,
        )
    return result


def eval_coeffs_to_slots(ctxt, cryptoContext, bootstrap_constants, bootstrap_plan):
    return coeffs_slots_conversion(
        ctxt,
        bootstrap_plan.c2s_plan,
        bootstrap_constants,
        bootstrap_plan,
        cryptoContext,
    )


def eval_slots_to_coeffs(ctxt, cryptoContext, bootstrap_constants, bootstrap_plan):
    return coeffs_slots_conversion(
        ctxt,
        bootstrap_plan.s2c_plan,
        bootstrap_constants,
        bootstrap_plan,
        cryptoContext,
    )


def _require_supported_transform_mode(level_budget):
    if int(level_budget[0]) == 1 and int(level_budget[1]) == 1:
        raise NotImplementedError("linear-transform bootstrap with level_budget=(1, 1) is not implemented")


def _mod_raise(cipher, L0, cryptoContext):
    cv = [
        F.cv_mod_raise(
            cv.reshape(1, 1, cv.shape[0], cv.shape[1]),
            L0,
            cryptoContext,
        ).reshape(-1, cryptoContext.N)
        for cv in cipher.cv
    ]
    return cipher.cipher_like(cv, L0)


def _mul_by_monomial_inplace(cipher, monomial_degree, cryptoContext):
    F.cv_mul_by_monomial(cipher.cv[0], cipher.cur_limbs, monomial_degree, cryptoContext)
    F.cv_mul_by_monomial(cipher.cv[1], cipher.cur_limbs, monomial_degree, cryptoContext)
    return cipher


def _validate_bootstrap_inputs(bootstrap_constants, bootstrap_plan):
    if bootstrap_constants is None:
        raise ValueError("homo_bootstrap requires bootstrap_constants generated by easyfhe.bs.openfhe.generate(ctx, ...)")
    if bootstrap_plan is None:
        raise ValueError("homo_bootstrap requires bootstrap_plan generated by easyfhe.bs.openfhe.generate(ctx, ...)")


def _raise_ciphertext(ciphertext, cryptoContext, bootstrap_constants, L0):
    correction_scale = bootstrap_constants._scalar_value("correction_scale")
    result = alignment.reduce_noise_to_one(ciphertext, cryptoContext)

    result = plaintext.homo_mul_scalar_double(result, correction_scale, cryptoContext)
    result = alignment.rescale_one_level(result, cryptoContext)

    result = _mod_raise(result, L0, cryptoContext)
    scalar = bootstrap_constants.encoded_scalars(
        "constant_eval_mult", result.cur_limbs, 1, cryptoContext, mode="double"
    )[0]
    return plaintext.homo_mul_scalar_double(result, scalar, cryptoContext)


def _scale_after_approx(ciphertext, cryptoContext, bootstrap_constants):
    scalar = bootstrap_constants.encoded_scalars(
        "post_scalar", ciphertext.cur_limbs, 0, cryptoContext, mode="int"
    )[0]
    return plaintext.homo_mul_scalar_int_inplace(
        ciphertext,
        scalar,
        cryptoContext,
    )


def _scale_to_original_message(ciphertext, cryptoContext, bootstrap_constants):
    scalar = bootstrap_constants.encoded_scalars(
        "cor_factor", ciphertext.cur_limbs, 0, cryptoContext, mode="int"
    )[0]
    return plaintext.homo_mul_scalar_int_inplace(
        ciphertext,
        scalar,
        cryptoContext,
    )


def _eval_bootstrap_approx(ciphertext, cryptoContext, bootstrap_constants, bootstrap_plan):
    return bootstrap_approx.eval_bootstrap_approx_mod(ciphertext, cryptoContext, bootstrap_constants, bootstrap_plan)


def _bootstrap_fully_packed(raised, cryptoContext, bootstrap_constants, bootstrap_plan):
    raised = alignment.reduce_noise_to_one(raised, cryptoContext)
    encoded = eval_coeffs_to_slots(raised, cryptoContext, bootstrap_constants, bootstrap_plan)

    conjugate = rotation.homo_rotate(encoded, 2 * cryptoContext.N - 1, cryptoContext)
    imag = arithmetic.homo_sub(encoded, conjugate, cryptoContext)
    real = arithmetic.homo_add(encoded, conjugate, cryptoContext, out=conjugate)
    imag = _mul_by_monomial_inplace(imag, 3 * cryptoContext.M // 4, cryptoContext)

    real = alignment.reduce_noise_to_one(real, cryptoContext)
    imag = alignment.reduce_noise_to_one(imag, cryptoContext)

    real = _eval_bootstrap_approx(real, cryptoContext, bootstrap_constants, bootstrap_plan)
    imag = _eval_bootstrap_approx(imag, cryptoContext, bootstrap_constants, bootstrap_plan)

    imag = _mul_by_monomial_inplace(imag, cryptoContext.M // 4, cryptoContext)
    encoded = arithmetic.homo_add(real, imag, cryptoContext, out=real)
    encoded = _scale_after_approx(encoded, cryptoContext, bootstrap_constants)
    encoded = alignment.reduce_noise_to_one(encoded, cryptoContext)
    return eval_slots_to_coeffs(encoded, cryptoContext, bootstrap_constants, bootstrap_plan)


def _replicate_sparse_slots(raised, slots, cryptoContext):
    for step in range(int(math.log2(cryptoContext.N // (2 * slots)))):
        raised = rotation.homo_rotate(
            raised,
            (1 << step) * slots,
            cryptoContext,
            addend=raised,
        )
    return raised.cipher_like(raised.cv, slots=slots)


def _restore_sparse_slots(decoded, slots, original_slots, cryptoContext):
    decoded = rotation.homo_rotate(decoded, slots, cryptoContext, addend=decoded)
    decoded = decoded.cipher_like(decoded.cv, slots=slots)
    return decoded.cipher_like(decoded.cv, slots=original_slots)


def _bootstrap_sparse(raised, original_slots, slots, cryptoContext, bootstrap_constants, bootstrap_plan):
    raised = _replicate_sparse_slots(raised, slots, cryptoContext)
    raised = alignment.reduce_noise_to_one(raised, cryptoContext)

    encoded = eval_coeffs_to_slots(raised, cryptoContext, bootstrap_constants, bootstrap_plan)
    encoded = rotation.homo_rotate(encoded, 2 * cryptoContext.N - 1, cryptoContext, addend=encoded)
    encoded = alignment.reduce_noise_to_one(encoded, cryptoContext)

    encoded = _eval_bootstrap_approx(encoded, cryptoContext, bootstrap_constants, bootstrap_plan)
    encoded = _scale_after_approx(encoded, cryptoContext, bootstrap_constants)
    encoded = alignment.reduce_noise_to_one(encoded, cryptoContext)

    decoded = eval_slots_to_coeffs(encoded, cryptoContext, bootstrap_constants, bootstrap_plan)
    return _restore_sparse_slots(decoded, slots, original_slots, cryptoContext)


# note: EvalBootstrap in ckksrns-fhe.cpp
def eval_bootstrap(ciphertext, cryptoContext, bootstrap_constants, bootstrap_plan, L0):
    _validate_bootstrap_inputs(bootstrap_constants, bootstrap_plan)

    if L0 is None:
        raise ValueError("bootstrap L0 must be explicit")
    _require_supported_transform_mode(bootstrap_plan.level_budget)

    slots = bootstrap_plan.slots
    raised = _raise_ciphertext(ciphertext, cryptoContext, bootstrap_constants, L0)
    if slots == cryptoContext.M // 4:
        decoded = _bootstrap_fully_packed(raised, cryptoContext, bootstrap_constants, bootstrap_plan)
    else:
        decoded = _bootstrap_sparse(raised, ciphertext.slots, slots, cryptoContext, bootstrap_constants, bootstrap_plan)

    decoded = _scale_to_original_message(decoded, cryptoContext, bootstrap_constants)
    return decoded.cipher_like(decoded.cv, slots=ciphertext.slots)


def homo_bootstrap(cipher, cryptoContext, bootstrap_constants, bootstrap_plan, L0):
    result = eval_bootstrap(cipher, cryptoContext, bootstrap_constants, bootstrap_plan, L0=L0)
    return alignment.reduce_noise_to_one(result, cryptoContext)
