#pragma once

#include <c10/macros/Macros.h>

#include <ATen/core/aten_interned_strings.h>
#include <ATen/core/symbol.h>

namespace c10 {

#define FORALL_NS_SYMBOLS(_)         \
  _(namespaces, prim)                \
  _(namespaces, prims)               \
  _(namespaces, nvprims)             \
  _(namespaces, aten)                \
  _(namespaces, cuda)                \
  _(namespaces, onnx)                \
  _(namespaces, attr)                \
  _(namespaces, scope)               \
  _(namespaces, user)                \
  _(namespaces, _caffe2)             \
  _(namespaces, dimname)             \
  _(namespaces, namespaces)          \
  _(prim, Assign)                    \
  _(prim, BroadcastingChunk)         \
  _(prim, BroadcastSizes)            \
  _(prim, ReductionSizes)            \
  _(prim, Constant)                  \
  _(prim, ChunkSizes)                \
  _(prim, ConstantMKLDNNTensor)      \
  _(prim, BroadcastMKLDNNTensors)    \
  _(prim, MKLDNNGroup)               \
  _(prim, MKLDNNHardSwish)           \
  _(prim, MKLDNNHardSigmoid)         \
  _(prim, MKLDNNHardTanh)            \
  _(prim, MKLDNNClamp)               \
  _(prim, StaticRuntimeCopyOuts)     \
  _(prim, Drop)                      \
  _(prim, Eval)                      \
  _(prim, Expand) /* onnx */         \
  _(prim, FusionGroup)               \
  _(prim, CudaFusionGroup)           \
  _(prim, CudaFusionGuard)           \
  _(prim, oneDNNFusionGroup)         \
  _(prim, oneDNNFusionGuard)         \
  _(prim, FunctionalGraph)           \
  _(prim, add_optional)              \
  _(prim, view_copy)                 \
  _(prim, permute_copy)              \
  _(prim, reshape_copy)              \
  _(prim, squeeze_copy)              \
  _(prim, t_copy)                    \
  _(prim, transpose_copy)            \
  _(prim, unsqueeze_copy)            \
  _(prim, flatten_copy)              \
  _(prim, expand_copy)               \
  _(prim, expand_as_copy)            \
  _(prim, DifferentiableGraph)       \
  _(prim, TensorExprGroup)           \
  _(prim, TensorExprDynamicGroup)    \
  _(prim, StaticSubgraph)            \
  _(prim, If)                        \
  _(prim, Jump) /* debug */          \
  _(prim, JumpNZ) /* debug */        \
  _(prim, JumpZ) /* debug */         \
  _(prim, Load)                      \
  _(prim, Loop)                      \
  _(prim, Param)                     \
  _(prim, PackPadded) /* onnx */     \
  _(prim, PadPacked) /* onnx */      \
  _(prim, Placeholder) /* debug */   \
  _(prim, Print)                     \
  _(prim, EmptyListLiteral)          \
  _(prim, LegacyTypedConstructor)    \
  _(prim, PythonOp)                  \
  _(prim, IgnoredPythonOp)           \
  _(prim, Reverse)                   \
  _(prim, Return)                    \
  _(prim, ReturnStmt)                \
  _(prim, BreakStmt)                 \
  _(prim, ContinueStmt)              \
  _(prim, ComprehensionScope)        \
  _(prim, Store)                     \
  _(prim, AutogradZero)              \
  _(prim, AutogradAnyNonZero)        \
  _(prim, AutogradAllNonZero)        \
  _(prim, AutogradAllZero)           \
  _(prim, Starred)                   \
  _(prim, TupleConstruct)            \
  _(prim, TupleUnpack)               \
  _(prim, TupleIndex)                \
  _(prim, TupleSlice)                \
  _(prim, ListConstruct)             \
  _(prim, ListUnpack)                \
  _(prim, DictConstruct)             \
  _(prim, ModuleContainerIndex)      \
  _(prim, EnumName)                  \
  _(prim, EnumValue)                 \
  _(prim, StringIndex)               \
  _(prim, NumToTensor)               \
  _(prim, Uninitialized)             \
  _(prim, VarConcat)                 \
  _(prim, VarStack)                  \
  _(prim, With)                      \
  _(prim, Enter)                     \
  _(prim, Exit)                      \
  _(prim, IfThenElse)                \
  _(aten, Bool)                      \
  _(aten, Int)                       \
  _(aten, FloatImplicit)             \
  _(aten, ComplexImplicit)           \
  _(aten, IntImplicit)               \
  _(aten, ScalarImplicit)            \
  _(aten, Float)                     \
  _(aten, Complex)                   \
  _(aten, str)                       \
  _(aten, Delete)                    \
  _(prim, device)                    \
  _(prim, dtype)                     \
  _(prim, layout)                    \
  _(prim, id)                        \
  _(prim, requires_grad)             \
  _(prim, MakeTestTensor) /* test */ \
  _(prim, AutogradAdd)               \
  _(prim, GradOf)                    \
  _(aten, grad)                      \
  _(aten, backward)                  \
  _(prim, Guard)                     \
  _(prim, BailOut)                   \
  _(prim, TypeCheck)                 \
  _(prim, RequiresGradCheck)         \
  _(prim, FallbackGraph)             \
  _(prim, FusedConcat)               \
  _(prim, ConstantChunk)             \
  _(prim, MMTreeReduce)              \
  _(prim, MMBatchSide)               \
  _(prim, list)                      \
  _(prim, dict)                      \
  _(prim, min)                       \
  _(prim, max)                       \
  _(prim, abs)                       \
  _(aten, divmod)                    \
  _(prim, zip)                       \
  _(prim, enumerate)                 \
  _(prim, range)                     \
  _(prim, rangelist)                 \
  _(prim, isinstance)                \
  _(prim, tolist)                    \
  _(prim, unchecked_cast)            \
  _(aten, _grad_sum_to_size)         \
  _(aten, _size_if_not_equal)        \
  _(aten, _ncf_unsqueeze)            \
  _(aten, warn)                      \
  _(aten, sorted)                    \
  _(aten, floordiv)                  \
  _(aten, __range_length)            \
  _(aten, __derive_index)            \
  _(aten, __round_to_zero_floordiv)  \
  _(aten, is_scripting)              \
  _(aten, _unwrap_optional)          \
  _(prim, fork)                      \
  _(prim, awaitable)                 \
  _(prim, forkClosure)               \
  _(prim, awaitableClosure)          \
  _(prim, awaitable_nowait)          \
  _(prim, awaitable_wait)            \
  _(prim, RaiseException)            \
  _(prim, Closure)                   \
  _(prim, CreateObject)              \
  _(prim, SetAttr)                   \
  _(prim, GetAttr)                   \
  _(prim, HasAttr)                   \
  _(prim, profile)                   \
  _(prim, profile_ivalue)            \
  _(prim, AddStatValue)              \
  _(prim, TimePoint)                 \
  _(prim, CallFunction)              \
  _(prim, CallMethod)                \
  _(prim, LoopContinuation)          \
  _(prim, annotate)                  \
  _(prim, TracedModuleForward)       \
  _(prim, TracedFork)                \
  _(prim, TracedAttr)                \
  _(prim, rpc_async)                 \
  _(prim, rpc_sync)                  \
  _(prim, rpc_remote)                \
  _(prim, is_cuda)                   \
  _(aten, append)                    \
  _(aten, as_tensor)                 \
  _(aten, adaptive_avg_pool2d_backward) \
  _(aten, format)                    \
  _(aten, percentFormat)             \
  _(aten, __not__)                   \
  _(aten, __is__)                    \
  _(aten, __isnot__)                 \
  _(aten, _ger)                      \
  _(aten, __getitem__)               \
  _(aten, _set_item)                 \
  _(aten, manual_seed)               \
  _(aten, device)                    \
  _(aten, hash)                      \
  _(aten, len)                       \
  _(aten, list)                      \
  _(aten, dict)                      \
  _(aten, wait)                      \
  _(aten, save)                      \
  _(aten, keys)                      \
  _(aten, ord)                       \
  _(aten, chr)                       \
  _(aten, hex)                       \
  _(aten, oct)                       \
  _(aten, clear)                     \
  _(aten, setdefault)                \
  _(aten, bin)                       \
  _(aten, pop)                       \
  _(aten, insert)                    \
  _(aten, tensor)                    \
  _(prim, unchecked_unwrap_optional) \
  _(aten, __contains__)              \
  _(prim, BailoutTemplate)           \
  _(prim, grad)                      \
  _(cuda, _set_device)               \
  _(cuda, set_stream)                \
  _(cuda, _current_device)           \
  _(cuda, synchronize)               \
  _(aten, has_torch_function)        \
  _(aten, is_autocast_enabled)       \
  _(aten, is_autocast_cpu_enabled)   \
  _(aten, is_autocast_xla_enabled)   \
  _(aten, get_autocast_dtype)        \
  _(aten, is_autocast_mps_enabled)   \
  _(aten, __interpolate) \
  _(aten, __upsample) \
  _(aten, __upsample_bilinear) \
  _(aten, __upsample_nearest) \
  _(aten, _adaptive_avg_pool2d) \
  _(aten, _add_relu) \
  _(aten, _add_relu_) \
  _(aten, _addmm_activation) \
  _(aten, _assert_int_or_pair) \
  _(aten, _batch_norm_impl_index) \
  _(aten, _batch_norm_with_update) \
  _(aten, _choose_qparams_per_tensor) \
  _(aten, _convert_indices_from_coo_to_csr) \
  _(aten, _convert_indices_from_csr_to_coo) \
  _(aten, _empty_affine_quantized) \
  _(aten, _foreach_norm) \
  _(aten, _fused_dropout) \
  _(aten, _get_cpu_capability) \
  _(aten, _get_tracing_state) \
  _(aten, _infer_size) \
  _(aten, _list_to_tensor) \
  _(aten, _log_softmax) \
  _(aten, _log_softmax_backward_data) \
  _(aten, _native_batch_norm_legit) \
  _(aten, _ncf_view) \
  _(aten, _nested_get) \
  _(aten, _no_grad_embedding_renorm_) \
  _(aten, _no_grad_fill_) \
  _(aten, _no_grad_normal_) \
  _(aten, _no_grad_uniform_) \
  _(aten, _no_grad_zero_) \
  _(aten, _pack_sequence) \
  _(aten, _saturate_weight_to_fp16) \
  _(aten, _slow_conv2d_backward) \
  _(aten, _slow_conv2d_forward) \
  _(aten, _softmax) \
  _(aten, _softmax_backward_data) \
  _(aten, _sparse_semi_structured_tile) \
  _(aten, _tensor_to_list) \
  _(aten, _transformer_encoder_layer_fwd) \
  _(aten, adaptive_avg_pool1d) \
  _(aten, adaptive_avg_pool2d) \
  _(aten, adaptive_avg_pool3d) \
  _(aten, adaptive_max_pool2d) \
  _(aten, adaptive_max_pool2d_backward) \
  _(aten, adaptive_max_pool3d) \
  _(aten, adaptive_max_pool3d_backward) \
  _(aten, alpha_dropout) \
  _(aten, avg_pool1d) \
  _(aten, avg_pool2d) \
  _(aten, avg_pool3d) \
  _(aten, batch_norm_stats) \
  _(aten, bilinear) \
  _(aten, broadcast_shapes) \
  _(aten, celu) \
  _(aten, cholesky_inverse) \
  _(aten, cholesky_solve) \
  _(aten, conv) \
  _(aten, convolution_backward) \
  _(aten, convrelu) \
  _(aten, cross) \
  _(aten, cross_entropy_loss) \
  _(aten, cudnn_batch_norm) \
  _(aten, cudnn_convolution_add_relu) \
  _(aten, cudnn_convolution_relu) \
  _(aten, dequantize) \
  _(aten, det) \
  _(aten, digamma) \
  _(aten, dist) \
  _(aten, dist_backward) \
  _(aten, dot) \
  _(aten, elu) \
  _(aten, elu_) \
  _(aten, elu_backward) \
  _(aten, embedding_renorm_) \
  _(aten, erfc) \
  _(aten, erfinv) \
  _(aten, feature_alpha_dropout) \
  _(aten, feature_dropout) \
  _(aten, feature_dropout_) \
  _(aten, gelu_) \
  _(aten, gelu_backward) \
  _(aten, ger) \
  _(aten, glu) \
  _(aten, gru) \
  _(aten, hardshrink) \
  _(aten, hardshrink_) \
  _(aten, hardshrink_backward) \
  _(aten, hardsigmoid_) \
  _(aten, hardsigmoid_backward) \
  _(aten, i0) \
  _(aten, index_put_impl_) \
  _(aten, inner) \
  _(aten, instance_norm) \
  _(aten, inverse) \
  _(aten, kron) \
  _(aten, leaky_relu) \
  _(aten, leaky_relu_) \
  _(aten, leaky_relu_backward) \
  _(aten, lgamma) \
  _(aten, linalg_cond) \
  _(aten, linalg_cross) \
  _(aten, linalg_det) \
  _(aten, linalg_diagonal) \
  _(aten, linalg_eigvals) \
  _(aten, linalg_householder_product) \
  _(aten, linalg_inv) \
  _(aten, linalg_matmul) \
  _(aten, linalg_matrix_exp) \
  _(aten, linalg_matrix_power) \
  _(aten, linalg_norm) \
  _(aten, linalg_solve) \
  _(aten, linalg_solve_triangular) \
  _(aten, linalg_tensorinv) \
  _(aten, logdet) \
  _(aten, lstm) \
  _(aten, matrix_exp) \
  _(aten, matrix_power) \
  _(aten, miopen_batch_norm) \
  _(aten, miopen_convolution_add_relu) \
  _(aten, miopen_convolution_relu) \
  _(aten, mish) \
  _(aten, mkldnn_convolution) \
  _(aten, mse_loss) \
  _(aten, multi_margin_loss) \
  _(aten, multilabel_margin_loss) \
  _(aten, native_batch_norm) \
  _(aten, native_batch_norm_backward) \
  _(aten, native_channel_shuffle) \
  _(aten, native_dropout) \
  _(aten, native_layer_norm) \
  _(aten, nll_loss_forward) \
  _(aten, nuclear_norm) \
  _(aten, orgqr) \
  _(aten, ormqr) \
  _(aten, outer) \
  _(aten, pinverse) \
  _(aten, polygamma) \
  _(aten, q_scale) \
  _(aten, q_zero_point) \
  _(aten, quantize_per_channel) \
  _(aten, quantize_per_tensor) \
  _(aten, quantized_gru) \
  _(aten, quantized_lstm) \
  _(aten, reflection_pad1d) \
  _(aten, reflection_pad2d) \
  _(aten, reflection_pad3d) \
  _(aten, relu6) \
  _(aten, relu6_) \
  _(aten, relu) \
  _(aten, replication_pad1d) \
  _(aten, replication_pad2d) \
  _(aten, replication_pad3d) \
  _(aten, rrelu) \
  _(aten, rrelu_with_noise) \
  _(aten, selu) \
  _(aten, silu_backward) \
  _(aten, soft_margin_loss) \
  _(aten, softplus) \
  _(aten, softplus_backward) \
  _(aten, softshrink) \
  _(aten, softshrink_backward) \
  _(aten, special_digamma) \
  _(aten, special_entr) \
  _(aten, special_erf) \
  _(aten, special_erfc) \
  _(aten, special_erfcx) \
  _(aten, special_erfinv) \
  _(aten, special_exp2) \
  _(aten, special_expit) \
  _(aten, special_expm1) \
  _(aten, special_gammainc) \
  _(aten, special_gammaincc) \
  _(aten, special_gammaln) \
  _(aten, special_i0) \
  _(aten, special_i0e) \
  _(aten, special_i1) \
  _(aten, special_i1e) \
  _(aten, special_log1p) \
  _(aten, special_log_ndtr) \
  _(aten, special_log_softmax) \
  _(aten, special_logit) \
  _(aten, special_logsumexp) \
  _(aten, special_multigammaln) \
  _(aten, special_ndtr) \
  _(aten, special_ndtri) \
  _(aten, special_polygamma) \
  _(aten, special_psi) \
  _(aten, special_round) \
  _(aten, special_sinc) \
  _(aten, special_softmax) \
  _(aten, special_xlog1py) \
  _(aten, special_xlogy) \
  _(aten, special_zeta) \
  _(aten, threshold) \
  _(aten, threshold_backward) \
  _(aten, upsample_bilinear2d) \
  _(aten, upsample_linear1d) \
  _(aten, upsample_nearest1d) \
  _(aten, upsample_nearest2d) \
  _(aten, upsample_nearest3d) \
  _(aten, upsample_trilinear3d) \
  _(aten, vdot) \
  _(aten, xlogy) \
  _(aten, Generator) \
  _(aten, ParallelThreadPoolNative) \
  _(aten, Size) \
  _(aten, _convolution) \
  _(aten, addbmm) \
  _(aten, addmm) \
  _(aten, addmv) \
  _(aten, addr) \
  _(aten, baddbmm) \
  _(aten, batch_norm) \
  _(aten, bmm) \
  _(aten, capitalize) \
  _(aten, center) \
  _(aten, confirmed_by_owner) \
  _(aten, conv1d) \
  _(aten, conv2d) \
  _(aten, conv3d) \
  _(aten, conv_tbc) \
  _(aten, conv_transpose1d) \
  _(aten, conv_transpose2d) \
  _(aten, conv_transpose3d) \
  _(aten, convolution) \
  _(aten, count) \
  _(aten, cpu) \
  _(aten, cuda) \
  _(aten, degrees) \
  _(aten, dropout) \
  _(aten, dropout_) \
  _(aten, dtype) \
  _(aten, einsum) \
  _(aten, element_size) \
  _(aten, embedding) \
  _(aten, embedding_bag) \
  _(aten, endswith) \
  _(aten, expandtabs) \
  _(aten, extend) \
  _(aten, fabs) \
  _(aten, factorial) \
  _(aten, find) \
  _(aten, foo) \
  _(aten, fork) \
  _(aten, gamma) \
  _(aten, gelu) \
  _(aten, get) \
  _(aten, getelem) \
  _(aten, group_norm) \
  _(aten, hardsigmoid) \
  _(aten, hardswish) \
  _(aten, hardswish_) \
  _(aten, hardtanh) \
  _(aten, hardtanh_) \
  _(aten, initial_seed) \
  _(aten, is_cuda) \
  _(aten, is_grad_enabled) \
  _(aten, is_non_overlapping_and_dense) \
  _(aten, is_owner) \
  _(aten, is_strides_like_format) \
  _(aten, isalnum) \
  _(aten, isalpha) \
  _(aten, isdecimal) \
  _(aten, isdigit) \
  _(aten, isidentifier) \
  _(aten, islower) \
  _(aten, isnumeric) \
  _(aten, isprintable) \
  _(aten, isspace) \
  _(aten, istitle) \
  _(aten, isupper) \
  _(aten, items) \
  _(aten, join) \
  _(aten, layer_norm) \
  _(aten, linear) \
  _(aten, ljust) \
  _(aten, local_value) \
  _(aten, lower) \
  _(aten, lstrip) \
  _(aten, mathremainder) \
  _(aten, matmul) \
  _(aten, mm) \
  _(aten, modf) \
  _(aten, mv) \
  _(aten, mvlgamma) \
  _(aten, owner) \
  _(aten, owner_name) \
  _(aten, partition) \
  _(aten, popitem) \
  _(aten, prelu) \
  _(aten, radians) \
  _(aten, relu_) \
  _(aten, remove) \
  _(aten, replace) \
  _(aten, reverse) \
  _(aten, rfind) \
  _(aten, rindex) \
  _(aten, rjust) \
  _(aten, rpartition) \
  _(aten, rsplit) \
  _(aten, rstrip) \
  _(aten, seed) \
  _(aten, set_grad_enabled) \
  _(aten, silu) \
  _(aten, silu_) \
  _(aten, softmax) \
  _(aten, splitlines) \
  _(aten, startswith) \
  _(aten, strip) \
  _(aten, swapcase) \
  _(aten, title) \
  _(aten, to_here) \
  _(aten, update) \
  _(aten, upper) \
  _(aten, warns) \
  _(aten, zfill) \
  FORALL_ATEN_BASE_SYMBOLS(_)        \
  _(onnx, Add)                       \
  _(onnx, Concat)                    \
  _(onnx, Constant)                  \
  _(onnx, ConstantFill)              \
  _(onnx, Div)                       \
  _(onnx, GRU)                       \
  _(onnx, Gather)                    \
  _(onnx, Gemm)                      \
  _(onnx, LSTM)                      \
  _(onnx, MatMul)                    \
  _(onnx, Min)                       \
  _(onnx, Max)                       \
  _(onnx, Mul)                       \
  _(onnx, Pow)                       \
  _(onnx, RNN)                       \
  _(onnx, Shape)                     \
  _(onnx, Size)                      \
  _(onnx, Slice)                     \
  _(onnx, Softmax)                   \
  _(onnx, Squeeze)                   \
  _(onnx, Sub)                       \
  _(onnx, Transpose)                 \
  _(onnx, Unsqueeze)                 \
  _(onnx, Loop)                      \
  _(onnx, If)                        \
  _(onnx, Reshape)                   \
  _(onnx, Expand)                    \
  _(onnx, Equal)                     \
  _(onnx, Greater)                   \
  _(onnx, GreaterOrEqual)            \
  _(onnx, Less)                      \
  _(onnx, LessOrEqual)               \
  _(onnx, Not)                       \
  _(aten, ATen)                      \
  _(onnx, Split)                     \
  _(onnx, ConstantOfShape)           \
  _(onnx, Cast)                      \
  _(onnx, Mod)                       \
  _(onnx, Sqrt)                      \
  _(onnx, SplitToSequence)           \
  _(onnx, SequenceAt)                \
  _(onnx, SequenceConstruct)         \
  _(onnx, SequenceEmpty)             \
  _(onnx, SequenceInsert)            \
  _(onnx, SequenceErase)             \
  _(onnx, ConcatFromSequence)        \
  _(onnx, Identity)                  \
  _(onnx, SoftmaxCrossEntropyLoss)   \
  _(onnx, NegativeLogLikelihoodLoss) \
  _(onnx, LogSoftmax)                \
  _(onnx, ReduceL1)                  \
  _(onnx, ReduceL2)                  \
  _(onnx, Conv)                      \
  _(onnx, BatchNormalization)        \
  _(onnx, ReduceMean)                \
  _(onnx, ReduceProd)                \
  _(onnx, Relu)                      \
  _(onnx, Neg)                       \
  _(onnx, NonZero)                   \
  _(onnx, Range)                     \
  _(onnx, Tile)                      \
  _(onnx, Where)                     \
  _(onnx, Optional)                  \
  _(onnx, OptionalGetElement)        \
  _(onnx, OptionalHasElement)        \
  FORALL_ATTR_BASE_SYMBOLS(_)        \
  _(attr, Subgraph)                  \
  _(attr, ReverseSubgraph)           \
  _(attr, f_real_outputs)            \
  _(attr, df_input_vjps)             \
  _(attr, df_input_captured_inputs)  \
  _(attr, df_input_captured_outputs) \
  _(attr, _outputs) \
  _(attr, bias) \
  _(attr, cudnn_enable) \
  _(attr, data_format) \
  _(attr, dilations) \
  _(attr, epsilon) \
  _(attr, exclude_pad) \
  _(attr, groups) \
  _(attr, hidden_size) \
  _(attr, keep_stats) \
  _(attr, kernel) \
  _(attr, max_val) \
  _(attr, min_val) \
  _(attr, momentum) \
  _(attr, normalized_shape) \
  _(attr, pads_begin) \
  _(attr, pads_end) \
  _(attr, rounding_type) \
  _(attr, running_mean) \
  _(attr, running_var) \
  _(attr, strides) \
  _(attr, train) \
  _(attr, training) \
  _(attr, transpose_b) \
  _(attr, weights_format) \
  _(attr, df_output_vjps)            \
  _(attr, axes)                      \
  _(attr, symbolic_shape_inputs)     \
  _(attr, allow_stack_outputs)       \
  _(attr, striding_inputs_desc)      \
  _(attr, striding_outputs_desc)     \
  _(attr, broadcast)                 \
  _(attr, direction)                 \
  _(attr, ends)                      \
  _(attr, inplace)                   \
  _(attr, input_as_shape)            \
  _(attr, is_zero)                   \
  _(attr, num_none)                  \
  _(attr, num_present)               \
  _(attr, perm)                      \
  _(attr, starts)                    \
  _(attr, profiled_type)             \
  _(attr, transA)                    \
  _(attr, transB)                    \
  _(attr, name)                      \
  _(attr, module)                    \
  _(attr, beg)                       \
  _(attr, idx)                       \
  _(attr, split)                     \
  _(attr, slot)                      \
  _(attr, kinds)                     \
  _(attr, types)                     \
  _(attr, scope)                     \
  _(attr, keepdims)                  \
  _(attr, cache_id)                  \
  _(attr, new_axis)                  \
  _(attr, warn_id)                   \
  _(attr, output_layouts)            \
  _(attr, allowzero)                 \
  _(attr, seen_none)                 \
  _(attr, overload_name)             \
  _(attr, node_stack_idx)

enum class _keys : unique_t {
    #define DEFINE_KEY(ns, s) ns##_##s,
    FORALL_NS_SYMBOLS(DEFINE_KEY)
    #undef DEFINE_KEY
    num_symbols
};

#define DEFINE_SYMBOL(ns, s) \
  namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
#undef DEFINE_SYMBOL

} // namespace c10
