#include <torch/csrc/python_headers.h>

namespace torch::autograd::generated {

void initialize_autogenerated_functions_0(PyObject* module) {}
void initialize_autogenerated_functions_1(PyObject* module) {}
void initialize_autogenerated_functions_2(PyObject* module) {}
void initialize_autogenerated_functions_3(PyObject* module) {}
void initialize_autogenerated_functions_4(PyObject* module) {}

} // namespace torch::autograd::generated
